/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.hibernate.bookstoreoracle;
import BLL.KhachHangDAO;
import DAL.KhachHang;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import DAL.Sach;
import BLL.HoaDonDAO;
import DAL.HoaDon;
import java.text.SimpleDateFormat;
import java.util.Date;
import BLL.CTHDDAO;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
/**
 *
 * @author DELL
 */
public class FindCustomer extends javax.swing.JInternalFrame {

    /**
     * Creates new form FindCustomer
     */
    KhachHangDAO kh = new KhachHangDAO();
    boolean TaoGioHang;
    ArrayList<Sach> ListSach;
    String mach;
    private Boolean flag = true; 
    public FindCustomer(boolean TaoGioHang,ArrayList<Sach> ListSach, String mach) {
        initComponents();
        load();
        this.TaoGioHang = TaoGioHang;
        this.ListSach = ListSach;
        XuLyTaoGioHang();
        this.mach = mach;
       jLabel6.setVisible(false);
        //Kiểm tra mỗi khi nhập makh
        txt_MaKH.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                if(flag==true)
                {
                    checkAndDisplayLabel();
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if(flag==true)
                {
                    checkAndDisplayLabel();
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                // Được gọi khi các thuộc tính của Document thay đổi (ít được sử dụng trong trường hợp JTextField)
            }
        });

    }
    private void checkAndDisplayLabel(){
        if(!kh.hienThiTenKH(txt_MaKH.getText()).equals("")){
            txt_TenKH.setText(kh.hienThiTenKH(txt_MaKH.getText()));
            jLabel6.setVisible(false);
        }else{
            jLabel6.setVisible(true);
        }
    }
    private void load()
    {
        txt_SDT.setVisible(false);
        txt_DiaChi.setVisible(false);
        lb_dchi.setVisible(false);
        lb_sdt.setVisible(false);
        btn_luu.setVisible(false);
        ArrayList<KhachHang> dsKH = kh.xuatThongTinKhachHang();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã KH");
        model.addColumn("Tên KH");
        model.addColumn("Số Điện Thoại");
        model.addColumn("Địa Chỉ");
         for (KhachHang kh : dsKH) {
            Object[] rowData = {kh.getMakh(), kh.getTenkh(), kh.getSDT(), kh.getDiachi()};
            model.addRow(rowData);
        }
        dgv_DSKH.setModel(model);
    }
    private void XuLyTaoGioHang()
    {
        if(TaoGioHang==true)
        {
             btn_okTaoGioHang.setVisible(true);
        }else
        {
           btn_okTaoGioHang.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dgv_DSKH = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_TenKH = new javax.swing.JTextField();
        lb_sdt = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        lb_dchi = new javax.swing.JLabel();
        txt_DiaChi = new javax.swing.JTextField();
        btn_ThemKH = new javax.swing.JButton();
        btn_SuaKH = new javax.swing.JButton();
        btn_TimKiemKH = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_MaKH = new javax.swing.JTextField();
        btn_okTaoGioHang = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(830, 467));

        dgv_DSKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dgv_DSKH);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("KHÁCH HÀNG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 30, -1, -1));

        jLabel2.setText("Tên khách hàng :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 127, -1, -1));

        txt_TenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenKHActionPerformed(evt);
            }
        });
        jPanel1.add(txt_TenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 124, 180, -1));

        lb_sdt.setText("SDT :");
        jPanel1.add(lb_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 205, -1, -1));

        txt_SDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SDTActionPerformed(evt);
            }
        });
        jPanel1.add(txt_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 205, 292, -1));

        lb_dchi.setText("Địa chỉ :");
        jPanel1.add(lb_dchi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, -1, -1));
        jPanel1.add(txt_DiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 233, 292, -1));

        btn_ThemKH.setText("Thêm");
        btn_ThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemKHActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ThemKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 158, 85, 35));

        btn_SuaKH.setText("Sửa");
        btn_SuaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaKHActionPerformed(evt);
            }
        });
        jPanel1.add(btn_SuaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 158, 86, 35));

        btn_TimKiemKH.setText("Tìm Kiếm");
        btn_TimKiemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemKHActionPerformed(evt);
            }
        });
        jPanel1.add(btn_TimKiemKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 90, -1, 56));

        jLabel5.setText("Mã khách hàng :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, -1, -1));

        txt_MaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaKHActionPerformed(evt);
            }
        });
        jPanel1.add(txt_MaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 90, 180, -1));

        btn_okTaoGioHang.setText("Tiếp tục");
        btn_okTaoGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okTaoGioHangActionPerformed(evt);
            }
        });
        jPanel1.add(btn_okTaoGioHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 369, 93, 53));

        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_luu, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 267, 93, 37));

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Không tìm thấy khách hàng");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenKHActionPerformed

    private void txt_SDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SDTActionPerformed
    
    private void btn_TimKiemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemKHActionPerformed
        // TODO add your handling code here:
        jLabel6.setVisible(false);
        ArrayList<KhachHang> dsKH = kh.timThongTinKhachHang(txt_MaKH.getText(), txt_TenKH.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã KH");
        model.addColumn("Tên KH");
        model.addColumn("Số Điện Thoại");
        model.addColumn("Địa Chỉ");
         for (KhachHang kh : dsKH) {
            Object[] rowData = {kh.getMakh(), kh.getTenkh(), kh.getSDT(), kh.getDiachi()};
            model.addRow(rowData);
        }
        dgv_DSKH.setModel(model);
    }//GEN-LAST:event_btn_TimKiemKHActionPerformed

    private void txt_MaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaKHActionPerformed

    HoaDonDAO hd = new HoaDonDAO();
    CTHDDAO cthd = new CTHDDAO();
    private void btn_okTaoGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okTaoGioHangActionPerformed
        // TODO add your handling code here:
        if(!txt_MaKH.getText().equals(""))
        {
            String mahd = hd.taoMaHoaDon();
            Date date = new Date();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String formattedDate = dateFormat.format(date);
            double tt= 0;
             for (Sach sa2 : ListSach) {
                 tt += sa2.gia*sa2.sl;
             }
            hd.taoHoaDon(mahd,txt_MaKH.getText(),formattedDate,mach,tt);
            for (Sach sa : ListSach) {
               cthd.taoCTHD(mahd, sa.getMasach(), sa.getSl());
            }
            JOptionPane.showMessageDialog(null,"Đã tạo hóa đơn thành công!");
            this.dispose();
        }
        else{
           JOptionPane.showMessageDialog(null,"Vui lòng nhập đầy đủ thông tin!");
        }
    }//GEN-LAST:event_btn_okTaoGioHangActionPerformed
    String chon;
    private void btn_ThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemKHActionPerformed
        if(lb_dchi.isVisible()==false)
        {
            txt_SDT.setVisible(true);
            txt_DiaChi.setVisible(true);
            lb_dchi.setVisible(true);
            lb_sdt.setVisible(true);
            btn_luu.setVisible(true);
            flag=false;
            Color col = new Color(220, 53, 53);
            btn_ThemKH.setForeground(col);
            btn_SuaKH.setForeground(Color.BLACK);
            chon="Them";
        }else if(lb_dchi.isVisible()==true && btn_SuaKH.getForeground()!=Color.BLACK)
        {
            txt_SDT.setVisible(true);
            txt_DiaChi.setVisible(true);
            lb_dchi.setVisible(true);
            lb_sdt.setVisible(true);
            btn_luu.setVisible(true);
            flag=false;
            Color col = new Color(220, 53, 53);
            btn_ThemKH.setForeground(col);
            btn_SuaKH.setForeground(Color.BLACK);
            chon="Them";
        }else
        {
            txt_SDT.setVisible(false);
            txt_DiaChi.setVisible(false);
            lb_dchi.setVisible(false);
            lb_sdt.setVisible(false);
            btn_luu.setVisible(false);
            flag=true;
            Color col = new Color(220, 53, 53);
            btn_ThemKH.setForeground(Color.BLACK);
            chon="Them";
        }
    }//GEN-LAST:event_btn_ThemKHActionPerformed

    private void btn_SuaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaKHActionPerformed
       if(lb_dchi.isVisible()==false)
        {
            txt_SDT.setVisible(true);
            txt_DiaChi.setVisible(true);
            lb_dchi.setVisible(true);
            lb_sdt.setVisible(true);
            btn_luu.setVisible(true);
            flag=false;
            Color col = new Color(220, 53, 53);
            btn_SuaKH.setForeground(col);
            btn_ThemKH.setForeground(Color.BLACK);
            chon="Sua";
        }else if(lb_dchi.isVisible()==true && btn_ThemKH.getForeground()!=Color.BLACK)
        {   
            txt_SDT.setVisible(true);
            txt_DiaChi.setVisible(true);
            lb_dchi.setVisible(true);
            lb_sdt.setVisible(true);
            btn_luu.setVisible(true);
            flag=false;
            Color col = new Color(220, 53, 53);
            btn_SuaKH.setForeground(col);
            btn_ThemKH.setForeground(Color.BLACK);
            chon="Sua";
        }else
        {
            txt_SDT.setVisible(false);
            txt_DiaChi.setVisible(false);
            lb_dchi.setVisible(false);
            lb_sdt.setVisible(false);
            btn_luu.setVisible(false);
            flag=true;
            Color col = new Color(220, 53, 53);
            btn_SuaKH.setForeground(Color.BLACK);
            chon="Sua";
        }
    }//GEN-LAST:event_btn_SuaKHActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        if(chon.equals("Them"))
        {
            if(txt_MaKH.getText()==""){
                return;
            }
            else if(txt_TenKH.getText()==""){
                return;
            }
            else{
                if(kh.createKhachHang(txt_MaKH.getText(), txt_TenKH.getText(), txt_SDT.getText(), txt_DiaChi.getText())==true){
                    JOptionPane.showMessageDialog(null,"Đã tạo Khách hàng : "+txt_TenKH.getText()+". Thành công!");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Vui lòng nhập đầy đủ thông tin!");
                }
            }
        }else if(chon.equals("Sua"))
        {
            if(txt_MaKH.getText()==""){
               return;
            }
            else if(txt_TenKH.getText()==""){
               return;
            }
            else{
               if(kh.updateKhachHang(txt_MaKH.getText(), txt_TenKH.getText(), txt_SDT.getText(), txt_DiaChi.getText())==true){
                   JOptionPane.showMessageDialog(null,"Đã update Khách hàng : "+txt_TenKH.getText()+". Thành công!");
               }
               else{
                   JOptionPane.showMessageDialog(null,"Vui lòng nhập đầy đủ thông tin!");
               }
            }
        }
        load();
    }//GEN-LAST:event_btn_luuActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_SuaKH;
    private javax.swing.JButton btn_ThemKH;
    private javax.swing.JButton btn_TimKiemKH;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_okTaoGioHang;
    private javax.swing.JTable dgv_DSKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_dchi;
    private javax.swing.JLabel lb_sdt;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_MaKH;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenKH;
    // End of variables declaration//GEN-END:variables
}
