/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.hibernate.bookstoreoracle;
import BLL.KhachHangDAO;
import DAL.KhachHang;
import java.util.ArrayList;
import javax.swing.table.DefaultTableModel;
import DAL.Sach;
import BLL.HoaDonDAO;
import DAL.HoaDon;
import java.text.SimpleDateFormat;
import java.util.Date;
import BLL.CTHDDAO;
import Bookstoreoracle.ReportManager;
import DAL.FieldReportClass;
import DAL.TotalReportClass;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.WriterException;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.DecimalFormat;
import java.util.List;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;
/**
 *
 * @author DELL
 */
public class FindCustomer extends javax.swing.JInternalFrame implements Runnable,ThreadFactory{

    KhachHangDAO kh = new KhachHangDAO();
    boolean TaoGioHang;
    ArrayList<Sach> ListSach;
    String mach;
    private Boolean flag = true;
    public FindCustomer(boolean TaoGioHang,ArrayList<Sach> ListSach, String mach) {
        initComponents();
        load();
        this.TaoGioHang = TaoGioHang;
        this.ListSach = ListSach;
        XuLyTaoGioHang();
        this.mach = mach;
       jLabel6.setVisible(false);
        //In hoa don
        try{
            ReportManager.getinstance().bienDichReport();
        }catch(Exception e)
        {
            e.printStackTrace();
        }
        //Kiểm tra mỗi khi nhập makh
        txt_MaKH.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                if(flag==true)
                {
                    checkAndDisplayLabel();
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                if(flag==true)
                {
                    checkAndDisplayLabel();
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                // Được gọi khi các thuộc tính của Document thay đổi (ít được sử dụng trong trường hợp JTextField)
            }
        });

    }
    private void checkAndDisplayLabel(){
        if(!kh.hienThiTenKH(txt_MaKH.getText()).equals("")){
            txt_TenKH.setText(kh.hienThiTenKH(txt_MaKH.getText()));
            jLabel6.setVisible(false);
        }else{
            jLabel6.setVisible(true);
        }
    }
    private void load()
    {
        txt_SDT.setVisible(false);
        txt_DiaChi.setVisible(false);
        lb_dchi.setVisible(false);
        lb_sdt.setVisible(false);
        btn_luu.setVisible(false);
        ArrayList<KhachHang> dsKH = kh.xuatThongTinKhachHang();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã KH");
        model.addColumn("Tên KH");
        model.addColumn("Số Điện Thoại");
        model.addColumn("Địa Chỉ");
         for (KhachHang kh : dsKH) {
            Object[] rowData = {kh.getMakh(), kh.getTenkh(), kh.getSDT(), kh.getDiachi()};
            model.addRow(rowData);
        }
        dgv_DSKH.setModel(model);
    }
    private void XuLyTaoGioHang()
    {
        if(TaoGioHang==true)
        {
             btn_okTaoGioHang.setVisible(true);
        }else
        {
           btn_okTaoGioHang.setVisible(false);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_TenKH = new javax.swing.JTextField();
        lb_sdt = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        lb_dchi = new javax.swing.JLabel();
        txt_DiaChi = new javax.swing.JTextField();
        btn_ThemKH = new javax.swing.JButton();
        btn_SuaKH = new javax.swing.JButton();
        btn_TimKiemKH = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txt_MaKH = new javax.swing.JTextField();
        btn_okTaoGioHang = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_Scan1 = new javax.swing.JButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        dgv_DSKH = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setPreferredSize(new java.awt.Dimension(830, 467));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("KHÁCH HÀNG");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 30, -1, -1));

        jLabel2.setText("Tên khách hàng :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 127, -1, -1));

        txt_TenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TenKHActionPerformed(evt);
            }
        });
        jPanel1.add(txt_TenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 124, 180, -1));

        lb_sdt.setText("SDT :");
        jPanel1.add(lb_sdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 205, -1, -1));

        txt_SDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_SDTActionPerformed(evt);
            }
        });
        jPanel1.add(txt_SDT, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 205, 292, -1));

        lb_dchi.setText("Địa chỉ :");
        jPanel1.add(lb_dchi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 236, -1, -1));
        jPanel1.add(txt_DiaChi, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 233, 292, -1));

        btn_ThemKH.setText("Thêm");
        btn_ThemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemKHActionPerformed(evt);
            }
        });
        jPanel1.add(btn_ThemKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(83, 158, 85, 35));

        btn_SuaKH.setText("Sửa");
        btn_SuaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaKHActionPerformed(evt);
            }
        });
        jPanel1.add(btn_SuaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 158, 86, 35));

        btn_TimKiemKH.setText("Tìm Kiếm");
        btn_TimKiemKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemKHActionPerformed(evt);
            }
        });
        jPanel1.add(btn_TimKiemKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 90, -1, 56));

        jLabel5.setText("Mã khách hàng :");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 93, -1, -1));

        txt_MaKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MaKHActionPerformed(evt);
            }
        });
        jPanel1.add(txt_MaKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 90, 180, -1));

        btn_okTaoGioHang.setText("Tiếp tục");
        btn_okTaoGioHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okTaoGioHangActionPerformed(evt);
            }
        });
        jPanel1.add(btn_okTaoGioHang, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 369, 93, 53));

        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_luu, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 267, 93, 37));

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Không tìm thấy khách hàng");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, -1, -1));

        btn_Scan1.setText("QR Scan");
        btn_Scan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Scan1MouseClicked(evt);
            }
        });
        jPanel1.add(btn_Scan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        dgv_DSKH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(dgv_DSKH);

        jLayeredPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_TenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TenKHActionPerformed

    private void txt_SDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_SDTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_SDTActionPerformed
    
    private void btn_TimKiemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemKHActionPerformed
        // TODO add your handling code here:
        jLabel6.setVisible(false);
        ArrayList<KhachHang> dsKH = kh.timThongTinKhachHang(txt_MaKH.getText(), txt_TenKH.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã KH");
        model.addColumn("Tên KH");
        model.addColumn("Số Điện Thoại");
        model.addColumn("Địa Chỉ");
         for (KhachHang kh : dsKH) {
            Object[] rowData = {kh.getMakh(), kh.getTenkh(), kh.getSDT(), kh.getDiachi()};
            model.addRow(rowData);
        }
        dgv_DSKH.setModel(model);
    }//GEN-LAST:event_btn_TimKiemKHActionPerformed

    private void txt_MaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MaKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MaKHActionPerformed

    HoaDonDAO hd = new HoaDonDAO();
    CTHDDAO cthd = new CTHDDAO();
    private boolean saveImage(byte[] imageBytes, String filePath) {
        try {
            Path path = Paths.get(filePath);
            Files.write(path, imageBytes);
            return true;
        } catch (IOException e) {
            e.printStackTrace();
            return false;
        }
    }
    public InputStream generateQR() throws WriterException{
        try{
            String QrCode = txt_MaKH.getText();
            String charset = "UTF-8";
            ByteArrayOutputStream out = QRCode.from(new String (QrCode.getBytes(charset),charset)).to(ImageType.PNG).stream();
            String f_name = txt_MaKH.getText();
            String path_name = "D:\\";
            if (saveImage(out.toByteArray(), path_name + f_name + ".png")) {
                return new ByteArrayInputStream(out.toByteArray());
            } else {
                System.out.println("Lỗi khi lưu hình ảnh QR code");
            }
        }catch(Exception e)
        {
            System.out.println("Lỗi");
        }
        return null;
    }
    private void btn_okTaoGioHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okTaoGioHangActionPerformed
        // TODO add your handling code here:
        if(!txt_MaKH.getText().equals(""))
        {
            String mahd = hd.taoMaHoaDon();
            Date date = new Date();
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            String formattedDate = dateFormat.format(date);
            double tt= 0;
             for (Sach sa2 : ListSach) {
                 tt += sa2.gia*sa2.sl;
             }
            hd.taoHoaDon(mahd,txt_MaKH.getText(),formattedDate,mach,tt);
           for (Sach sa : ListSach) {
               cthd.taoCTHD(mahd, sa.getMasach(), sa.getSl());
            }
            int choice = JOptionPane.showConfirmDialog(null, "Tạo hóa đơn thành công! Bạn muốn in hóa đơn thành công không?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (choice == JOptionPane.YES_OPTION) {
                try{
                    List<FieldReportClass> fields = new ArrayList<>();
                    // Tạo mẫu định dạng tiền VND với chấm phân tách mỗi 3 số
                    DecimalFormat decimalFormat = new DecimalFormat("###,###,###.##");
                    for (Sach sa3 : ListSach) {
                        
                        String GIA = decimalFormat.format(sa3.getGia());
                        String THANHTIEN = decimalFormat.format(sa3.getSl()*sa3.getGia());
                        fields.add(new FieldReportClass(sa3.getTensach(),sa3.getSl(),GIA,THANHTIEN));
                    }
                    decimalFormat = new DecimalFormat("###,###,###.## VND");
                    String THANHTIEN = decimalFormat.format(tt);
                    TotalReportClass dataprint = new TotalReportClass(mahd, txt_TenKH.getText(), THANHTIEN, generateQR(), fields);
                    ReportManager.getinstance().printReport(dataprint);
                }catch(Exception e)
                {
                    e.printStackTrace();
                }
            }
            this.dispose();
        }
        else{
           JOptionPane.showMessageDialog(null,"Vui lòng nhập đầy đủ thông tin!");
        }
    }//GEN-LAST:event_btn_okTaoGioHangActionPerformed
    String chon;
    private void btn_ThemKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemKHActionPerformed
        if(lb_dchi.isVisible()==false)
        {
            txt_SDT.setVisible(true);
            txt_DiaChi.setVisible(true);
            lb_dchi.setVisible(true);
            lb_sdt.setVisible(true);
            btn_luu.setVisible(true);
            flag=false;
            jLabel6.setVisible(false);
            Color col = new Color(220, 53, 53);
            btn_ThemKH.setForeground(col);
            btn_SuaKH.setForeground(Color.BLACK);
            chon="Them";
        }else if(lb_dchi.isVisible()==true && btn_SuaKH.getForeground()!=Color.BLACK)
        {
            txt_SDT.setVisible(true);
            txt_DiaChi.setVisible(true);
            lb_dchi.setVisible(true);
            lb_sdt.setVisible(true);
            btn_luu.setVisible(true);
            flag=false;
            jLabel6.setVisible(false);
            Color col = new Color(220, 53, 53);
            btn_ThemKH.setForeground(col);
            btn_SuaKH.setForeground(Color.BLACK);
            chon="Them";
        }else
        {
            txt_SDT.setVisible(false);
            txt_DiaChi.setVisible(false);
            lb_dchi.setVisible(false);
            lb_sdt.setVisible(false);
            btn_luu.setVisible(false);
            flag=true;
            jLabel6.setVisible(true);
            Color col = new Color(220, 53, 53);
            btn_ThemKH.setForeground(Color.BLACK);
            chon="Them";
        }
    }//GEN-LAST:event_btn_ThemKHActionPerformed

    private void btn_SuaKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaKHActionPerformed
       if(lb_dchi.isVisible()==false)
        {
            txt_SDT.setVisible(true);
            txt_DiaChi.setVisible(true);
            lb_dchi.setVisible(true);
            lb_sdt.setVisible(true);
            btn_luu.setVisible(true);
            flag=false;
            jLabel6.setVisible(false);
            Color col = new Color(220, 53, 53);
            btn_SuaKH.setForeground(col);
            btn_ThemKH.setForeground(Color.BLACK);
            chon="Sua";
        }else if(lb_dchi.isVisible()==true && btn_ThemKH.getForeground()!=Color.BLACK)
        {   
            txt_SDT.setVisible(true);
            txt_DiaChi.setVisible(true);
            lb_dchi.setVisible(true);
            lb_sdt.setVisible(true);
            btn_luu.setVisible(true);
            flag=false;
            jLabel6.setVisible(false);
            Color col = new Color(220, 53, 53);
            btn_SuaKH.setForeground(col);
            btn_ThemKH.setForeground(Color.BLACK);
            chon="Sua";
        }else
        {
            txt_SDT.setVisible(false);
            txt_DiaChi.setVisible(false);
            lb_dchi.setVisible(false);
            lb_sdt.setVisible(false);
            btn_luu.setVisible(false);
            flag=true;
            jLabel6.setVisible(true);
            Color col = new Color(220, 53, 53);
            btn_SuaKH.setForeground(Color.BLACK);
            chon="Sua";
        }
    }//GEN-LAST:event_btn_SuaKHActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        if(chon.equals("Them"))
        {
            if(txt_MaKH.getText()==""){
                return;
            }
            else if(txt_TenKH.getText()==""){
                return;
            }
            else{
                if(kh.createKhachHang(txt_MaKH.getText(), txt_TenKH.getText(), txt_SDT.getText(), txt_DiaChi.getText())==true){
                    JOptionPane.showMessageDialog(null,"Đã tạo Khách hàng : "+txt_TenKH.getText()+". Thành công!");
                }
                else{
                    JOptionPane.showMessageDialog(null,"Vui lòng nhập đầy đủ thông tin!");
                }
            }
        }else if(chon.equals("Sua"))
        {
            if(txt_MaKH.getText()==""){
               return;
            }
            else if(txt_TenKH.getText()==""){
               return;
            }
            else{
               if(kh.updateKhachHang(txt_MaKH.getText(), txt_TenKH.getText(), txt_SDT.getText(), txt_DiaChi.getText())==true){
                   JOptionPane.showMessageDialog(null,"Đã update Khách hàng : "+txt_TenKH.getText()+". Thành công!");
               }
               else{
                   JOptionPane.showMessageDialog(null,"Vui lòng nhập đầy đủ thông tin!");
               }
            }
        }
        load();
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_Scan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Scan1MouseClicked
        SetLayoutScan();
    }//GEN-LAST:event_btn_Scan1MouseClicked
    private JPanel Scanscreen;
    private JButton btn_timSach;
    private WebcamPanel panel = null;
    private Webcam webcam = null;
    private Executor executor = Executors.newSingleThreadExecutor(this);
     private void btn_TimSachClicked(java.awt.event.MouseEvent evt) {
        btn_timSach.setVisible(false);
        Scanscreen.setVisible(false);
        jLayeredPane1.setVisible(true);
        btn_Scan1.setVisible(true);
        btn_TimKiemKH.setVisible(true);
        flag =true;
         // Đóng webcam khi nút được nhấn
        webcam.close();
    }
    
    private void SetLayoutScan()
    {
        jLayeredPane1.setVisible(false);
        btn_Scan1.setVisible(false);
        btn_TimKiemKH.setVisible(false);
        jLabel6.setVisible(false);
        flag =false;
        btn_timSach = new JButton();
        btn_timSach.setText("Tìm theo nhập liệu");
        btn_timSach.setBounds(450, 10, 150, 30);
        btn_timSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TimSachClicked(evt);
            }
        });
        Scanscreen = new JPanel();
        Scanscreen.setBounds(5, 30, 422, 390);
        Scanscreen.setBackground(Color.black);
        this.add(btn_timSach);
        this.add(Scanscreen);
        jPanel1.setBounds(435, 20, jPanel1.getWidth(), jPanel1.getHeight());
        this.add(jPanel1);
        initWebcam();
    }
    private void initWebcam()
    {
        Dimension size = WebcamResolution.QVGA.getSize();
        webcam = Webcam.getWebcams().get(0);
        webcam.setViewSize(size);
        panel = new WebcamPanel(webcam);
        panel.setPreferredSize(size);
        panel.setFPSDisplayed(true);
        Scanscreen.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,470, 300));
        executor.execute(this);
    }
    @Override
    public void run(){
        do{
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(FindBook.class.getName()).log(Level.SEVERE, null, ex);
            }
            Result result = null;
            BufferedImage image = null;
            if(webcam.isOpen())
            {
                if((image = webcam.getImage())==null)
                {
                    continue;
                }
            }
            LuminanceSource source = new BufferedImageLuminanceSource(image);
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
            
            try {
                result = new MultiFormatReader().decode(bitmap);
            } catch (NotFoundException ex) {
                Logger.getLogger(FindBook.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(result != null)
            {
                LoadKHQR(result.getText());
            }
        }while(true);
    }
    private void LoadKHQR(String makh) {                                         
        // TODO add your handling code here:
        ArrayList<KhachHang> dsKH = kh.timThongTinKhachHang(makh, makh);
        if(dsKH.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Không tìm thấy khách hàng cần tìm!");
            return;
        }
         for (KhachHang kh : dsKH) {
            txt_MaKH.setText(kh.getMakh());
            txt_TenKH.setText(kh.getTenkh());
            txt_DiaChi.setText(kh.getDiachi());
            txt_SDT.setText(kh.getSDT());
        }
    }  
    @Override
    public Thread newThread(Runnable r)
    {
        Thread t = new Thread(r,"My Thread");
        t.setDaemon(true);
        return t;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Scan1;
    private javax.swing.JButton btn_SuaKH;
    private javax.swing.JButton btn_ThemKH;
    private javax.swing.JButton btn_TimKiemKH;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_okTaoGioHang;
    private javax.swing.JTable dgv_DSKH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_dchi;
    private javax.swing.JLabel lb_sdt;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_MaKH;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenKH;
    // End of variables declaration//GEN-END:variables
}
