/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.hibernate.bookstoreoracle;

import javax.swing.table.DefaultTableModel;
import BLL.UserDAO;
import java.awt.event.ItemListener;
import java.util.ArrayList;
import javax.swing.JOptionPane;
/**
 *
 * @author DELL
 */
public class GrantUser extends javax.swing.JInternalFrame {

    /**
     * Creates new form GrantUser
     */
    String tenuser;
    public GrantUser(String tenuser) {
        initComponents();
        this.tenuser = tenuser;
        load();
        buttonGroup1.add(rdo_nv);
        buttonGroup1.add(rdo_ql);
    }
    UserDAO op = new UserDAO();
    private void load()
    {
        ArrayList<String> ds = op.xuatThongTinUser();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("USERNAME");
         for (String user : ds) {
             //Lọc nhân viên có chữ bắt đầu bằng NV
            if(user.startsWith("NV"))
            {
                Object[] rowData = {user};
                model.addRow(rowData);
            }
        }
        dgv_dsuser.setModel(model);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        txt_tenuser = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        dgv_dsuser = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        rdo_ql = new javax.swing.JRadioButton();
        rdo_nv = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        btn_reset = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel2.setText("Tên user:");

        dgv_dsuser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dgv_dsuser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgv_dsuserMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(dgv_dsuser);

        jLabel4.setText("DANH SÁCH USER");

        jButton4.setText("Tìm");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        rdo_ql.setText("Quản lý");
        rdo_ql.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdo_qlMouseClicked(evt);
            }
        });

        rdo_nv.setText("Nhân viên");
        rdo_nv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rdo_nvMouseClicked(evt);
            }
        });

        jLabel5.setText("Vai trò:");

        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jButton4)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_reset))
                                    .addComponent(txt_tenuser, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(rdo_ql)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rdo_nv))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jLabel4)))
                .addContainerGap(168, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txt_tenuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(btn_reset))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdo_ql)
                            .addComponent(rdo_nv)
                            .addComponent(jLabel5))))
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        ArrayList<String> ds = op.timThongTinUser(txt_tenuser.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("USERNAME");
         for (String user : ds) {
            //Lọc nhân viên có chữ bắt đầu bằng NV
            if(user.startsWith("NV"))
            {
                Object[] rowData = {user};
                model.addRow(rowData);
            }
        }
        dgv_dsuser.setModel(model);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        load();
    }//GEN-LAST:event_btn_resetActionPerformed
    private boolean voHieuHoaEvent = false;
    private void dgv_dsuserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgv_dsuserMouseClicked
        // TODO add your handling code here:
        int row = dgv_dsuser.rowAtPoint(evt.getPoint());
        if (row >= 0 ) {
            Object user = dgv_dsuser.getValueAt(row, 0);
            voHieuHoaEvent = true;
            rdo_ql.setSelected(false);
            rdo_nv.setSelected(false);
            if(op.kiemTraRoleUser(user.toString()).equals("QL"))
            {
                rdo_ql.setSelected(true);
            }else if(op.kiemTraRoleUser(user.toString()).equals("NV"))
            {
                rdo_nv.setSelected(true);
            }else
            {
                op.ganRoleUser("nv", user.toString());
                rdo_nv.setSelected(true);
            }
            txt_tenuser.setText(user.toString());
            voHieuHoaEvent = false;
        }
    }//GEN-LAST:event_dgv_dsuserMouseClicked

    private void rdo_qlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdo_qlMouseClicked
        // TODO add your handling code here:
        if (!voHieuHoaEvent) {
            if(op.thuHoiRoleUser("nv", txt_tenuser.getText())==true && op.ganRoleUser("ql", txt_tenuser.getText())==true)
            { 
                JOptionPane.showMessageDialog(null, "Thay đổi quyền thành công!");
            }
        }
    }//GEN-LAST:event_rdo_qlMouseClicked

    private void rdo_nvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rdo_nvMouseClicked
        // TODO add your handling code here:
        if (!voHieuHoaEvent ) {
            if(op.thuHoiRoleUser("ql", txt_tenuser.getText())==true && op.ganRoleUser("nv", txt_tenuser.getText())==true)
            { 
                JOptionPane.showMessageDialog(null, "Thay đổi quyền thành công!");
            }
        }
    }//GEN-LAST:event_rdo_nvMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_reset;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable dgv_dsuser;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JRadioButton rdo_nv;
    private javax.swing.JRadioButton rdo_ql;
    private javax.swing.JTextField txt_tenuser;
    // End of variables declaration//GEN-END:variables
}
