/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.hibernate.bookstoreoracle;

import BLL.OracleProvider;
import java.sql.Connection;
import javax.swing.JOptionPane;
/**
 *
 * @author tuann
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    private static OracleProvider op = new OracleProvider();
    private static Connection connect=null;
    private static String mach = null;
    public Login(String url, String name, String machnew) {
        initComponents();
        cb_tencuahang.addItem("CUAHANGSACH2"); 
//        cb_tencuahang.addItem("CUAHANGSACH3"); 
        cb_tencuahang.addItem("CUAHANGSACH1"); 
        cb_tencuahang.getItemAt(0);
        this.mach = "CH02";
        boolean ktname = false;
        for (int i = 0; i < cb_tencuahang.getItemCount(); i++) {
            if (name != null && name.equals(cb_tencuahang.getItemAt(i))) {
                ktname = true;
                break;
            }
        }
        if(!ktname && url!=null)
        {
            this.mach = machnew;
            cb_tencuahang.addItem(name);
            // Lấy item tại vị trí mới thêm vào
            int lastIndex = cb_tencuahang.getItemCount()- 1;
            cb_tencuahang.setSelectedIndex(lastIndex);
            cb_tencuahang.enable(false);
            op.setUrl(url);
        }
        // Thiết lập nút mặc định khi nhấn phím Enter
        this.getRootPane().setDefaultButton(jButton1);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txt_tendn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_doich = new javax.swing.JButton();
        cb_tencuahang = new javax.swing.JComboBox<>();
        txt_mk = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tên đăng nhập");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mật khẩu");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Đăng nhập");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_tendn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("LOGIN");

        btn_doich.setText("Thêm cửa hàng");
        btn_doich.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doichActionPerformed(evt);
            }
        });

        cb_tencuahang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_tencuahangItemStateChanged(evt);
            }
        });

        txt_mk.setMinimumSize(new java.awt.Dimension(64, 26));
        txt_mk.setPreferredSize(new java.awt.Dimension(64, 26));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_doich)
                        .addGap(18, 18, 18)
                        .addComponent(cb_tencuahang, 0, 234, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_tendn, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                            .addComponent(txt_mk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(16, 16, 16))
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLabel3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(txt_tendn, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(txt_mk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_doich, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_tencuahang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tendn = txt_tendn.getText();
        String matkhau = txt_mk.getText();
        op.setUsername(tendn);
        op.setPassword(matkhau);
        connect=op.getConnection();
        if(connect!=null){
            JOptionPane.showMessageDialog(null,"Kết nối thành công!");
            Home hm = new Home(mach,txt_tendn.getText());
            this.dispose();      
            hm.show();
        }
        else{
            JOptionPane.showMessageDialog(null,"Kết nối thất bại!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btn_doichActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doichActionPerformed
        // TODO add your handling code here:
        ChangeStore hm = new ChangeStore(); 
        this.dispose();
        hm.show();
    }//GEN-LAST:event_btn_doichActionPerformed

    private void cb_tencuahangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_tencuahangItemStateChanged
        // TODO add your handling code here:
        if(cb_tencuahang.getSelectedItem() == null || cb_tencuahang.getSelectedItem().equals("CUAHANGSACH1"))
        {
            op.setIp("112.197.63.187");
            op.setPort("1521");
            op.setService("CUAHANGSACH1");
            op.setUrl("jdbc:oracle:thin:@112.197.63.187:1521:CUAHANGSACH1");
            mach = "CH01";
        }
        else if(cb_tencuahang.getSelectedItem() == null || cb_tencuahang.getSelectedItem().equals("CUAHANGSACH2"))
        {
            op.setIp("171.235.167.112");
            op.setPort("1521");
            op.setService("CUAHANGSACH2");
            op.setUrl("jdbc:oracle:thin:@171.235.167.112:1521:CUAHANGSACH2");
             mach = "CH02";
        }
//        else if(cb_tencuahang.getSelectedItem().equals("CUAHANGSACH3"))
//        {
//            op.setIp("112.197.63.187");
//            op.setPort("1522");
//            op.setService("CUAHANGSACH3");
//            op.setUrl("jdbc:oracle:thin:@112.197.63.187:1522:CUAHANGSACH3");
//             mach = "CH03";
//        }
    }//GEN-LAST:event_cb_tencuahangItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login(null,null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_doich;
    private javax.swing.JComboBox<String> cb_tencuahang;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField txt_mk;
    private javax.swing.JTextField txt_tendn;
    // End of variables declaration//GEN-END:variables
}
