/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package com.hibernate.bookstoreoracle;

import BLL.SachDAO;
import DAL.Sach;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.NotFoundException;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.image.BufferedImage;
import java.util.ArrayList;
import java.util.concurrent.Executor;
import java.util.concurrent.Executors;
import java.util.concurrent.ThreadFactory;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author DELL
 */
public class MakeOrder extends javax.swing.JInternalFrame implements Runnable,ThreadFactory{

    /**
     * Creates new form MakeOrder
     */
    String mach;
    private DefaultTableModel giohang;
            
    public MakeOrder(String mach) {
        initComponents();
        Color col = new Color(250, 242, 211);
        getContentPane().setBackground(col);
        load();
        this.mach=mach;
        giohang = new DefaultTableModel();
        giohang.addColumn("Mã Sách");
        giohang.addColumn("Tên Sách");
        giohang.addColumn("Giá Bán");
        giohang.addColumn("Số lượng");
    }
    SachDAO sach = new SachDAO();
    private void load()
    {
        ArrayList<Sach> dsKH = sach.xuatThongTinSach();
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã Sách");
        model.addColumn("Tên Sách");
        model.addColumn("Giá Bán");
        model.addColumn("SL Tồn");
         for (Sach kh : dsKH) {
            Object[] rowData = {kh.getMasach(), kh.getTensach(), kh.getGia(), kh.getSl()};
            model.addRow(rowData);
        }
        dgv_DSSACH.setModel(model);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane10 = new javax.swing.JLayeredPane();
        panel12 = new java.awt.Panel();
        jLabel45 = new javax.swing.JLabel();
        jScrollPane13 = new javax.swing.JScrollPane();
        dgv_DSSACH = new javax.swing.JTable();
        btn_tim1 = new javax.swing.JButton();
        jLayeredPane11 = new javax.swing.JLayeredPane();
        btn_ok = new javax.swing.JButton();
        txt_soluong10 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        txt_giasach10 = new javax.swing.JTextField();
        txt_tensach = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        btn_themgiohang = new javax.swing.JButton();
        pn_giohang = new java.awt.Panel();
        jLabel50 = new javax.swing.JLabel();
        jScrollPane12 = new javax.swing.JScrollPane();
        dgv_giohang = new javax.swing.JTable();
        txt_masach = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        btn_resetgiohang = new javax.swing.JButton();
        btn_Scan1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);

        panel12.setBackground(new java.awt.Color(204, 236, 248));

        jLabel45.setText("THÔNG TIN SÁCH");

        javax.swing.GroupLayout panel12Layout = new javax.swing.GroupLayout(panel12);
        panel12.setLayout(panel12Layout);
        panel12Layout.setHorizontalGroup(
            panel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel12Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel45)
                .addGap(174, 174, 174))
        );
        panel12Layout.setVerticalGroup(
            panel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel45)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dgv_DSSACH.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        dgv_DSSACH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dgv_DSSACHMouseClicked(evt);
            }
        });
        jScrollPane13.setViewportView(dgv_DSSACH);

        btn_tim1.setText("Tìm theo tên sách");
        btn_tim1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tim1ActionPerformed(evt);
            }
        });

        jLayeredPane10.setLayer(panel12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane10.setLayer(jScrollPane13, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane10.setLayer(btn_tim1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane10Layout = new javax.swing.GroupLayout(jLayeredPane10);
        jLayeredPane10.setLayout(jLayeredPane10Layout);
        jLayeredPane10Layout.setHorizontalGroup(
            jLayeredPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_tim1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jLayeredPane10Layout.setVerticalGroup(
            jLayeredPane10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_tim1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        btn_ok.setText("Tiếp tục");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        jLabel42.setText("Số lượng");

        jLabel44.setText("Giá  sách");

        jLabel43.setText("Tên sách");

        panel1.setBackground(new java.awt.Color(34, 9, 44));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 8, Short.MAX_VALUE)
        );

        btn_themgiohang.setText("Thêm vào giỏ hàng");
        btn_themgiohang.setToolTipText("");
        btn_themgiohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themgiohangActionPerformed(evt);
            }
        });

        pn_giohang.setBackground(new java.awt.Color(204, 236, 248));

        jLabel50.setText("GIỎ HÀNG");

        javax.swing.GroupLayout pn_giohangLayout = new javax.swing.GroupLayout(pn_giohang);
        pn_giohang.setLayout(pn_giohangLayout);
        pn_giohangLayout.setHorizontalGroup(
            pn_giohangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_giohangLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jLabel50)
                .addGap(155, 155, 155))
        );
        pn_giohangLayout.setVerticalGroup(
            pn_giohangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_giohangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel50, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        dgv_giohang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane12.setViewportView(dgv_giohang);

        jLabel46.setText("Mã sách");

        btn_resetgiohang.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btn_resetgiohang.setForeground(new java.awt.Color(255, 0, 51));
        btn_resetgiohang.setText("Tạo lại giỏ hàng");
        btn_resetgiohang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetgiohangActionPerformed(evt);
            }
        });

        jLayeredPane11.setLayer(btn_ok, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(txt_soluong10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(jLabel42, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(jLabel44, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(txt_giasach10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(txt_tensach, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(jLabel43, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(panel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(btn_themgiohang, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(pn_giohang, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(jScrollPane12, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(txt_masach, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(jLabel46, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane11.setLayer(btn_resetgiohang, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane11Layout = new javax.swing.GroupLayout(jLayeredPane11);
        jLayeredPane11.setLayout(jLayeredPane11Layout);
        jLayeredPane11Layout.setHorizontalGroup(
            jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredPane11Layout.createSequentialGroup()
                        .addGroup(jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel44)
                            .addComponent(jLabel43))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tensach, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txt_giasach10)))
                    .addGroup(jLayeredPane11Layout.createSequentialGroup()
                        .addComponent(jLabel46)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_masach))
                    .addGroup(jLayeredPane11Layout.createSequentialGroup()
                        .addGroup(jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jLayeredPane11Layout.createSequentialGroup()
                                    .addComponent(jLabel42)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txt_soluong10, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btn_themgiohang))
                                .addComponent(btn_resetgiohang)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pn_giohang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jLayeredPane11Layout.setVerticalGroup(
            jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jLayeredPane11Layout.createSequentialGroup()
                .addGroup(jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_masach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel46)))
                    .addComponent(pn_giohang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jLayeredPane11Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane12, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(jLayeredPane11Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_tensach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel43))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_giasach10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel44))
                        .addGap(23, 23, 23)
                        .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jLayeredPane11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_themgiohang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_soluong10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel42))
                        .addGap(18, 18, 18)
                        .addComponent(btn_resetgiohang, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        btn_Scan1.setText("QR Scan");
        btn_Scan1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_Scan1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Scan1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLayeredPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Scan1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLayeredPane10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLayeredPane11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private JPanel Scanscreen;
    private JButton btn_timSach;
    private WebcamPanel panel = null;
    private Webcam webcam = null;
    private Executor executor = Executors.newSingleThreadExecutor(this);
    private void SetLayoutScan()
    {
        jLayeredPane10.setVisible(false);
        btn_Scan1.setVisible(false);
        btn_timSach = new JButton();
        btn_timSach.setText("Tìm theo nhập liệu");
        btn_timSach.setBounds(530, 10, 190, 30);
        btn_timSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_TimSachClicked(evt);
            }
        });
        Scanscreen = new JPanel();
        Scanscreen.setBounds(200, 45, 350, 250);
        Scanscreen.setBackground(Color.black);
        Scanscreen.add(btn_timSach);
        this.add(btn_timSach);
        this.add(Scanscreen);
//        jLayeredPane11.setBounds(10, 350, jLayeredPane11.getWidth(), jLayeredPane11.getHeight());
//        this.add(jLayeredPane11);
        initWebcam();
    }
    private void btn_TimSachClicked(java.awt.event.MouseEvent evt) {
        
        btn_timSach.setVisible(false);
        Scanscreen.setVisible(false);
        jLayeredPane10.setVisible(true);
        btn_Scan1.setVisible(true);
        // Đóng webcam khi nút được nhấn
        webcam.close();
    }
    private void btn_Scan1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_Scan1MouseClicked
        SetLayoutScan();
    }//GEN-LAST:event_btn_Scan1MouseClicked

    private void btn_tim1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tim1ActionPerformed
        // TODO add your handling code here:
        ArrayList<Sach> dsKH = sach.timThongTinSach(txt_tensach.getText(),txt_masach.getText());
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Mã Sách");
        model.addColumn("Tên Sách");
        model.addColumn("Giá Bán");
        model.addColumn("SL Tồn");
         for (Sach kh : dsKH) {
            Object[] rowData = {kh.getMasach(), kh.getTensach(), kh.getGia(), kh.getSl()};
            model.addRow(rowData);
        }
        dgv_DSSACH.setModel(model);
    }//GEN-LAST:event_btn_tim1ActionPerformed

    private int slton;
    private void dgv_DSSACHMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dgv_DSSACHMouseClicked
        // TODO add your handling code here:
        int row = dgv_DSSACH.rowAtPoint(evt.getPoint());
        if (row >= 0 ) {
            Object ma = dgv_DSSACH.getValueAt(row, 0);
            txt_masach.setText(ma.toString());
            Object ten = dgv_DSSACH.getValueAt(row, 1);
            txt_tensach.setText(ten.toString().trim());
            Object gia = dgv_DSSACH.getValueAt(row, 2);
            txt_giasach10.setText(gia.toString());
            Object sl = dgv_DSSACH.getValueAt(row, 3);
            slton = Integer.parseInt(sl.toString());
        }
    }//GEN-LAST:event_dgv_DSSACHMouseClicked
    public static boolean isNumeric(String str) {
            return str.matches("\\d+");
    }
    private boolean KtTrungGioHang(String masach) {
    for (int i = 0; i < giohang.getRowCount(); i++) {
        if (giohang.getValueAt(i, 0).equals(masach)) {
            return true;
        }
    }
    return false;
}
    private void btn_themgiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themgiohangActionPerformed
        // TODO add your handling code here:
        if(isNumeric(txt_soluong10.getText())==true && Integer.parseInt(txt_soluong10.getText())>0 && Integer.parseInt(txt_soluong10.getText())<=slton)
        {
            String masach = txt_masach.getText();
            if (!KtTrungGioHang(masach)) {
                Object[] rowData = {txt_masach.getText(), txt_tensach.getText(), txt_giasach10.getText(), txt_soluong10.getText()};
                giohang.addRow(rowData);
                dgv_giohang.setModel(giohang);
            }else {
                JOptionPane.showMessageDialog(null, "Sách đã tồn tại trong giỏ hàng.");
            }
        }else
        {
            JOptionPane.showMessageDialog(null,"Nhập sai số lượng!");
        }
    }//GEN-LAST:event_btn_themgiohangActionPerformed

    private void btn_resetgiohangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetgiohangActionPerformed
        // TODO add your handling code here:
        giohang.setRowCount(0);
        dgv_giohang.setModel(giohang);
    }//GEN-LAST:event_btn_resetgiohangActionPerformed
    
    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // TODO add your handling code here:
        ArrayList<Sach> GioHang = new ArrayList<Sach>();
        for (int i = 0; i < giohang.getRowCount(); i++) {
            Sach e = new Sach();
            e.setMasach(giohang.getValueAt(i, 0).toString());
            e.setTensach(giohang.getValueAt(i, 1).toString());
            e.setGia(Integer.parseInt(giohang.getValueAt(i, 2).toString()));
            e.setSl(Integer.parseInt(giohang.getValueAt(i, 3).toString()));
            GioHang.add(e);
        }
        FindCustomer cus = new FindCustomer(true,GioHang, mach);
        // Tìm Form cha
        JFrame parentFrame = (JFrame) SwingUtilities.getWindowAncestor(this);
        JDesktopPane trangchu = ((Home)parentFrame).getDesktopPane();
        trangchu.add(cus, JLayeredPane.PALETTE_LAYER);
        this.dispose();
        cus.setVisible(true);
    }//GEN-LAST:event_btn_okActionPerformed
    private void initWebcam()
    {
        Dimension size = WebcamResolution.QVGA.getSize();
        webcam = Webcam.getWebcams().get(0);
        webcam.setViewSize(size);
        panel = new WebcamPanel(webcam);
        panel.setPreferredSize(size);
        panel.setFPSDisplayed(true);
        Scanscreen.add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0,0,470, 300));
        executor.execute(this);
    }
    @Override
    public void run(){
        do{
            try {
                Thread.sleep(100);
            } catch (InterruptedException ex) {
                Logger.getLogger(FindBook.class.getName()).log(Level.SEVERE, null, ex);
            }
            Result result = null;
            BufferedImage image = null;
            if(webcam.isOpen())
            {
                if((image = webcam.getImage())==null)
                {
                    continue;
                }
            }
            LuminanceSource source = new BufferedImageLuminanceSource(image);
            BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));
            
            try {
                result = new MultiFormatReader().decode(bitmap);
            } catch (NotFoundException ex) {
                Logger.getLogger(FindBook.class.getName()).log(Level.SEVERE, null, ex);
            }
            if(result != null)
            {
                LoadSachQR(result.getText());
            }
        }while(true);
    }
    private void LoadSachQR(String tensach) {                                         
        // TODO add your handling code here:
        ArrayList<Sach> dsKH = sach.timThongTinSach(tensach,tensach);
        if(dsKH.isEmpty())
        {
            JOptionPane.showMessageDialog(null,"Không tìm thấy sách cần tìm!");
            return;
        }
         for (Sach kh : dsKH) {
            txt_masach.setText(kh.getMasach());
            txt_tensach.setText(kh.getTensach());
            txt_giasach10.setText(String.valueOf(kh.getGia()));
            txt_soluong10.setText(String.valueOf(kh.getSl()));
        }
    }  
    @Override
    public Thread newThread(Runnable r)
    {
        Thread t = new Thread(r,"My Thread");
        t.setDaemon(true);
        return t;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Scan1;
    private javax.swing.JButton btn_ok;
    private javax.swing.JButton btn_resetgiohang;
    private javax.swing.JButton btn_themgiohang;
    private javax.swing.JButton btn_tim1;
    private javax.swing.JTable dgv_DSSACH;
    private javax.swing.JTable dgv_giohang;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLayeredPane jLayeredPane10;
    private javax.swing.JLayeredPane jLayeredPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private java.awt.Panel panel1;
    private java.awt.Panel panel12;
    private java.awt.Panel pn_giohang;
    private javax.swing.JTextField txt_giasach10;
    private javax.swing.JTextField txt_masach;
    private javax.swing.JTextField txt_soluong10;
    private javax.swing.JTextField txt_tensach;
    // End of variables declaration//GEN-END:variables
}
